name: Build and Release

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Print current directory
        run: pwd

      
      # Extract previous release version
      - name: Extract previous release version
        id: extract_previous_version
        run: |
          previous_tag=$(git describe --abbrev=0 --tags)
          previous_version=$(echo "${previous_tag}" | sed 's/V//')
          echo "::set-output name=previous_version::${previous_version}"

      # Increment version
      - name: Increment version
        id: increment_version
        run: |
          major=$(echo "${{ steps.extract_previous_version.outputs.previous_version }}" | cut -d'.' -f1)
          minor=$(echo "${{ steps.extract_previous_version.outputs.previous_version }}" | cut -d'.' -f2)
          new_minor=$((minor + 1))
          new_version="${major}.${new_minor}.0_beta"
          echo "::set-output name=new_version::${new_version}"

      # Set new version
      - name: Set new version
        run: echo "export APP_VERSION=${{ steps.increment_version.outputs.new_version }}" >> $GITHUB_ENV

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      # Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      # Install npm dependencies
      - name: Install npm dependencies
        run: npm install

      # Build assets with npm
      - name: Build assets with npm
        run: npm run build

        # Copy .env.example to .env
      - name: Copy .env.example to .env
        run: cp .env.example .env
      # Tar project contents with version
      - name: Tar project contents with version
        run: |
          version=${{ steps.increment_version.outputs.new_version }}
          zip -r "cssbans_${version}.zip" .
  
        
      - name: Set Git user identity
        run: |
          git config --global user.email "yuvim86@gmail.com"
          git config --global user.name "hobsRKM"
      # Create tag for new version
      - name: Create tag for new version
        run: git tag -a "v${{ steps.increment_version.outputs.new_version }}" -m "Release v${{ steps.increment_version.outputs.new_version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload zip file to release
      - name: Upload tar file to release
        uses: actions/upload-artifact@v2
        with:
          name: project
          path: cssbans_*.zip
      # Download artifact from URL
      - name: Download artifact
        run: wget -O artifact.zip https://github.com/counterstrikesharp-panel/css-bans/releases/download/1.1.4/serverlistplayersfix_windows.zip && wget https://github.com/counterstrikesharp-panel/css-bans/releases/download/1.1.4/serverlistplayersfix_linux.zip
      
      # Copy artifact to current directory
      - name: Copy artifact to current directory
        run: serverlistplayersfix_windows.zip . && cp serverlistplayersfix_linux.zip .
           
      # Copy previous release artifacts to new release
      - name: Copy previous release artifacts to new release
        run: cp previous_release/serverlistplayersfix_windows.zip . && cp previous_release/serverlistplayersfix_linux.zip .
