name: Releases

on: 
 push:
    tags:
    - '*'

jobs:
 build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 17

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-interaction --no-suggest

    - name: Install NPM dependencies
      run: npm install

    - name: Compile assets
      run: npm run build
    - name: Copy default env
      run: cp .env.example .env
    - name: Zip Project Contents
      run: zip -r cssbans.v${{ github.ref_name }}.zip .
    - name: Create Draft Release with Specific File Name and Generate Release Notes
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "cssbans.v${{ github.ref_name }}.zip"
        bodyFile: "body.md"
        draft: true
        generate_release_notes: true
