name: Create Tag Example

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Git user identity
        run: |
          git config --global user.email "yuvim86@gmail.com"
          git config --global user.name "hobsRKM"
      - name: List tags before tag creation
        run: git tag -l

      - name: Create tag
        run: git tag -a "v1.1.5" -m "Tag check"

      - name: List tags after tag creation
        run: git tag -l
